/**
 * Guarded service-worker registration for Heartbeat.
 *
 * The service worker is generated by vite-plugin-pwa (generateSW) and
 * served at /sw.js in production. We register it only when ALL of the
 * following are true:
 *   - running in a production build
 *   - not inside an iframe (Lovable's editor preview embeds the app)
 *   - hostname is not a Lovable preview / dev / beta surface
 *   - URL does not carry ?sw=off (kill switch)
 *
 * In any refused context we proactively unregister any matching SW so a
 * stale registration left over from an earlier visit can't keep serving
 * old HTML.
 */

const SW_URL = "/sw.js";

function isRefusedHost(hostname: string): boolean {
  if (hostname.startsWith("id-preview--") || hostname.startsWith("preview--")) return true;
  if (hostname === "lovableproject.com" || hostname.endsWith(".lovableproject.com")) return true;
  if (hostname === "lovableproject-dev.com" || hostname.endsWith(".lovableproject-dev.com")) return true;
  if (hostname === "beta.lovable.dev" || hostname.endsWith(".beta.lovable.dev")) return true;
  return false;
}

async function unregisterMatching() {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      regs
        .filter((r) => {
          const url = r.active?.scriptURL || r.installing?.scriptURL || r.waiting?.scriptURL || "";
          return url.endsWith(SW_URL);
        })
        .map((r) => r.unregister()),
    );
  } catch {
    // best-effort
  }
}

export function registerServiceWorker() {
  if (typeof window === "undefined") return;
  if (!("serviceWorker" in navigator)) return;

  if (!import.meta.env.PROD) {
    void unregisterMatching();
    return;
  }

  const inIframe = window.self !== window.top;
  const url = new URL(window.location.href);
  const killSwitch = url.searchParams.get("sw") === "off";

  if (inIframe || isRefusedHost(window.location.hostname) || killSwitch) {
    void unregisterMatching();
    return;
  }

  // Defer until after first paint to avoid contention with hydration.
  window.addEventListener("load", () => {
    navigator.serviceWorker.register(SW_URL, { scope: "/" }).catch(() => {
      // Silent: SW is a progressive enhancement.
    });
  });
}
